version: '3.5'

services:

  #  The Application
  app:
    container_name: app
    build:
      context: ./docker
    volumes:
      - ./code/:/var/www/code/
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_HOST=db
      - REDIS_HOST=cache

  # The Web Server
  server:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "8081:81"
      - "9443:443"
    volumes:
      - ./code/:/var/www/code/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  # The Database
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
      
  # PHP Myadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - 8080:80
    links:
        - db
    environment:
        PMA_HOST: db

  # The Redis
  cache:
    image: redis:4.0.11
    container_name: redis
    ports:
      - 6379:6379