FROM php:7.3-fpm

WORKDIR /var/www/code/

RUN chown -R 777 /var/www/code/

RUN export DEBIAN_FRONTEND=noninteractive && \
apt-get update -yqq && \
apt-get install -y nano && \
apt-get install -y curl && \
apt-get install -y apt-utils zip unzip && \
apt-get install -y libzip-dev libpq-dev && \
docker-php-ext-install pdo_mysql && \
docker-php-ext-install mysqli && \
docker-php-ext-configure zip && \
docker-php-ext-install zip && \
apt-get install -y sendmail libpng-dev && \
apt-get install -y zlib1g-dev 

RUN docker-php-ext-install mbstring

RUN docker-php-ext-install gd

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN composer global require laravel/installer \
&& export PATH="~/.composer/vendor/bin:$PATH" \
&& echo 'PATH="~/.composer/vendor/bin:$PATH"' >> ~/.bashrc \
&& /bin/bash -c 'source ~/.bashrc'

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
&& apt-get update && apt-get install -y nodejs

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
